### ISSUE TITLE
README.md doesn't really explain how to use the module

### ISSUE THREAD

**Issue by bschonec** [ScaleCommerce/puppet-sc_random#1]
I've been trying for about an hour to implement your module but based on the readme, I've not been able to create any random data.

Using the hiera examples, all I get is blank data.

Can you double-check that the readme has enough information to be able to create random data variables?

The [Use Random Resources](https://github.com/ScaleCommerce/puppet-sc_random#use-random-resources-in-hiera) via Hiera doesn't work at all.  If I follow the directions in [Use random resources in other modules](https://github.com/ScaleCommerce/puppet-sc_random#use-random-resources-in-other-modules) I am successful.

**Comment by bschonec** [comment]
@adriankirchner @ThomasLohner @lroehrs

**Comment by lroehrs** [comment]
Hi @bschonec,
we're still using this module on this way:

* Added to the modules dir
* Hiera config:

```
classes:
  - sc_random

sc_random::numbers:
  backup-minute:
    max: 59
  backup-hour:
    max: 7

crons:
  backup:
    ...
    hour: "%{sc_random::number.backup-hour}"
    minute: "%{sc_random::number.backup-minute}"
```

Hope that helps you already. :)
